//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_base_movement_Teleport;
        
        private static SteamVR_Action_Boolean p_base_movement_ConfirmTarget;
        
        private static SteamVR_Action_Boolean p_base_movement_StopRobot;
        
        private static SteamVR_Action_Pose p_base_movement_Pose;
        
        private static SteamVR_Action_Single p_base_movement_Squeeze;
        
        private static SteamVR_Action_Boolean p_base_movement_HeadsetOnHead;
        
        private static SteamVR_Action_Vector2 p_base_movement_ThumbXY;
        
        private static SteamVR_Action_Vector2 p_base_movement_StrafeTarget;
        
        private static SteamVR_Action_Boolean p_base_movement_TurnCamLeft;
        
        private static SteamVR_Action_Boolean p_base_movement_TurnCamRight;
        
        private static SteamVR_Action_Boolean p_base_movement_moveForward;
        
        private static SteamVR_Action_Boolean p_base_movement_moveBackward;
        
        private static SteamVR_Action_Vibration p_base_movement_Haptic;
        
        private static SteamVR_Action_Vector2 p_arm_movement_targetPosition;
        
        private static SteamVR_Action_Pose p_arm_movement_pose;
        
        private static SteamVR_Action_Boolean p_arm_movement_targetConfirm;
        
        private static SteamVR_Action_Boolean p_arm_movement_changeControlMode;
        
        private static SteamVR_Action_Boolean p_arm_movement_actuateGripper;
        
        private static SteamVR_Action_Boolean p_arm_movement_stopArm;
        
        private static SteamVR_Action_Vector2 p_arm_movement_targetRotationAndHeight;
        
        private static SteamVR_Action_Boolean p_arm_movement_NoResponse;
        
        private static SteamVR_Action_Boolean p_arm_movement_YesResponse;
        
        private static SteamVR_Action_Pose p_common_controls_Pose;
        
        private static SteamVR_Action_Boolean p_common_controls_ChangeActionSet;
        
        private static SteamVR_Action_Boolean p_common_controls_Select;
        
        private static SteamVR_Action_Boolean p_common_controls_Activate;
        
        private static SteamVR_Action_Boolean p_common_controls_Interface;
        
        private static SteamVR_Action_Boolean p_common_controls_ActivateMenu;
        
        private static SteamVR_Action_Boolean p_common_controls_SelectMenu;
        
        private static SteamVR_Action_Vector2 p_common_controls_MenuCursorPosition;
        
        public static SteamVR_Action_Boolean base_movement_Teleport
        {
            get
            {
                return SteamVR_Actions.p_base_movement_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean base_movement_ConfirmTarget
        {
            get
            {
                return SteamVR_Actions.p_base_movement_ConfirmTarget.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean base_movement_StopRobot
        {
            get
            {
                return SteamVR_Actions.p_base_movement_StopRobot.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose base_movement_Pose
        {
            get
            {
                return SteamVR_Actions.p_base_movement_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Single base_movement_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_base_movement_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean base_movement_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_base_movement_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 base_movement_ThumbXY
        {
            get
            {
                return SteamVR_Actions.p_base_movement_ThumbXY.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 base_movement_StrafeTarget
        {
            get
            {
                return SteamVR_Actions.p_base_movement_StrafeTarget.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean base_movement_TurnCamLeft
        {
            get
            {
                return SteamVR_Actions.p_base_movement_TurnCamLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean base_movement_TurnCamRight
        {
            get
            {
                return SteamVR_Actions.p_base_movement_TurnCamRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean base_movement_moveForward
        {
            get
            {
                return SteamVR_Actions.p_base_movement_moveForward.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean base_movement_moveBackward
        {
            get
            {
                return SteamVR_Actions.p_base_movement_moveBackward.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration base_movement_Haptic
        {
            get
            {
                return SteamVR_Actions.p_base_movement_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vector2 arm_movement_targetPosition
        {
            get
            {
                return SteamVR_Actions.p_arm_movement_targetPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Pose arm_movement_pose
        {
            get
            {
                return SteamVR_Actions.p_arm_movement_pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean arm_movement_targetConfirm
        {
            get
            {
                return SteamVR_Actions.p_arm_movement_targetConfirm.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean arm_movement_changeControlMode
        {
            get
            {
                return SteamVR_Actions.p_arm_movement_changeControlMode.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean arm_movement_actuateGripper
        {
            get
            {
                return SteamVR_Actions.p_arm_movement_actuateGripper.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean arm_movement_stopArm
        {
            get
            {
                return SteamVR_Actions.p_arm_movement_stopArm.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 arm_movement_targetRotationAndHeight
        {
            get
            {
                return SteamVR_Actions.p_arm_movement_targetRotationAndHeight.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean arm_movement_NoResponse
        {
            get
            {
                return SteamVR_Actions.p_arm_movement_NoResponse.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean arm_movement_YesResponse
        {
            get
            {
                return SteamVR_Actions.p_arm_movement_YesResponse.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose common_controls_Pose
        {
            get
            {
                return SteamVR_Actions.p_common_controls_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean common_controls_ChangeActionSet
        {
            get
            {
                return SteamVR_Actions.p_common_controls_ChangeActionSet.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean common_controls_Select
        {
            get
            {
                return SteamVR_Actions.p_common_controls_Select.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean common_controls_Activate
        {
            get
            {
                return SteamVR_Actions.p_common_controls_Activate.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean common_controls_Interface
        {
            get
            {
                return SteamVR_Actions.p_common_controls_Interface.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean common_controls_ActivateMenu
        {
            get
            {
                return SteamVR_Actions.p_common_controls_ActivateMenu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean common_controls_SelectMenu
        {
            get
            {
                return SteamVR_Actions.p_common_controls_SelectMenu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 common_controls_MenuCursorPosition
        {
            get
            {
                return SteamVR_Actions.p_common_controls_MenuCursorPosition.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.base_movement_Teleport,
                    SteamVR_Actions.base_movement_ConfirmTarget,
                    SteamVR_Actions.base_movement_StopRobot,
                    SteamVR_Actions.base_movement_Pose,
                    SteamVR_Actions.base_movement_Squeeze,
                    SteamVR_Actions.base_movement_HeadsetOnHead,
                    SteamVR_Actions.base_movement_ThumbXY,
                    SteamVR_Actions.base_movement_StrafeTarget,
                    SteamVR_Actions.base_movement_TurnCamLeft,
                    SteamVR_Actions.base_movement_TurnCamRight,
                    SteamVR_Actions.base_movement_moveForward,
                    SteamVR_Actions.base_movement_moveBackward,
                    SteamVR_Actions.base_movement_Haptic,
                    SteamVR_Actions.arm_movement_targetPosition,
                    SteamVR_Actions.arm_movement_pose,
                    SteamVR_Actions.arm_movement_targetConfirm,
                    SteamVR_Actions.arm_movement_changeControlMode,
                    SteamVR_Actions.arm_movement_actuateGripper,
                    SteamVR_Actions.arm_movement_stopArm,
                    SteamVR_Actions.arm_movement_targetRotationAndHeight,
                    SteamVR_Actions.arm_movement_NoResponse,
                    SteamVR_Actions.arm_movement_YesResponse,
                    SteamVR_Actions.common_controls_Pose,
                    SteamVR_Actions.common_controls_ChangeActionSet,
                    SteamVR_Actions.common_controls_Select,
                    SteamVR_Actions.common_controls_Activate,
                    SteamVR_Actions.common_controls_Interface,
                    SteamVR_Actions.common_controls_ActivateMenu,
                    SteamVR_Actions.common_controls_SelectMenu,
                    SteamVR_Actions.common_controls_MenuCursorPosition};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.base_movement_Teleport,
                    SteamVR_Actions.base_movement_ConfirmTarget,
                    SteamVR_Actions.base_movement_StopRobot,
                    SteamVR_Actions.base_movement_Pose,
                    SteamVR_Actions.base_movement_Squeeze,
                    SteamVR_Actions.base_movement_HeadsetOnHead,
                    SteamVR_Actions.base_movement_ThumbXY,
                    SteamVR_Actions.base_movement_StrafeTarget,
                    SteamVR_Actions.base_movement_TurnCamLeft,
                    SteamVR_Actions.base_movement_TurnCamRight,
                    SteamVR_Actions.base_movement_moveForward,
                    SteamVR_Actions.base_movement_moveBackward,
                    SteamVR_Actions.arm_movement_targetPosition,
                    SteamVR_Actions.arm_movement_pose,
                    SteamVR_Actions.arm_movement_targetConfirm,
                    SteamVR_Actions.arm_movement_changeControlMode,
                    SteamVR_Actions.arm_movement_actuateGripper,
                    SteamVR_Actions.arm_movement_stopArm,
                    SteamVR_Actions.arm_movement_targetRotationAndHeight,
                    SteamVR_Actions.arm_movement_NoResponse,
                    SteamVR_Actions.arm_movement_YesResponse,
                    SteamVR_Actions.common_controls_Pose,
                    SteamVR_Actions.common_controls_ChangeActionSet,
                    SteamVR_Actions.common_controls_Select,
                    SteamVR_Actions.common_controls_Activate,
                    SteamVR_Actions.common_controls_Interface,
                    SteamVR_Actions.common_controls_ActivateMenu,
                    SteamVR_Actions.common_controls_SelectMenu,
                    SteamVR_Actions.common_controls_MenuCursorPosition};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.base_movement_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.base_movement_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.base_movement_Pose,
                    SteamVR_Actions.arm_movement_pose,
                    SteamVR_Actions.common_controls_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.base_movement_Teleport,
                    SteamVR_Actions.base_movement_ConfirmTarget,
                    SteamVR_Actions.base_movement_StopRobot,
                    SteamVR_Actions.base_movement_HeadsetOnHead,
                    SteamVR_Actions.base_movement_TurnCamLeft,
                    SteamVR_Actions.base_movement_TurnCamRight,
                    SteamVR_Actions.base_movement_moveForward,
                    SteamVR_Actions.base_movement_moveBackward,
                    SteamVR_Actions.arm_movement_targetConfirm,
                    SteamVR_Actions.arm_movement_changeControlMode,
                    SteamVR_Actions.arm_movement_actuateGripper,
                    SteamVR_Actions.arm_movement_stopArm,
                    SteamVR_Actions.arm_movement_NoResponse,
                    SteamVR_Actions.arm_movement_YesResponse,
                    SteamVR_Actions.common_controls_ChangeActionSet,
                    SteamVR_Actions.common_controls_Select,
                    SteamVR_Actions.common_controls_Activate,
                    SteamVR_Actions.common_controls_Interface,
                    SteamVR_Actions.common_controls_ActivateMenu,
                    SteamVR_Actions.common_controls_SelectMenu};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.base_movement_Squeeze};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.base_movement_ThumbXY,
                    SteamVR_Actions.base_movement_StrafeTarget,
                    SteamVR_Actions.arm_movement_targetPosition,
                    SteamVR_Actions.arm_movement_targetRotationAndHeight,
                    SteamVR_Actions.common_controls_MenuCursorPosition};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.base_movement_Teleport,
                    SteamVR_Actions.base_movement_ConfirmTarget,
                    SteamVR_Actions.base_movement_StopRobot,
                    SteamVR_Actions.base_movement_Squeeze,
                    SteamVR_Actions.base_movement_HeadsetOnHead,
                    SteamVR_Actions.base_movement_ThumbXY,
                    SteamVR_Actions.base_movement_StrafeTarget,
                    SteamVR_Actions.base_movement_TurnCamLeft,
                    SteamVR_Actions.base_movement_TurnCamRight,
                    SteamVR_Actions.base_movement_moveForward,
                    SteamVR_Actions.base_movement_moveBackward,
                    SteamVR_Actions.arm_movement_targetPosition,
                    SteamVR_Actions.arm_movement_targetConfirm,
                    SteamVR_Actions.arm_movement_changeControlMode,
                    SteamVR_Actions.arm_movement_actuateGripper,
                    SteamVR_Actions.arm_movement_stopArm,
                    SteamVR_Actions.arm_movement_targetRotationAndHeight,
                    SteamVR_Actions.arm_movement_NoResponse,
                    SteamVR_Actions.arm_movement_YesResponse,
                    SteamVR_Actions.common_controls_ChangeActionSet,
                    SteamVR_Actions.common_controls_Select,
                    SteamVR_Actions.common_controls_Activate,
                    SteamVR_Actions.common_controls_Interface,
                    SteamVR_Actions.common_controls_ActivateMenu,
                    SteamVR_Actions.common_controls_SelectMenu,
                    SteamVR_Actions.common_controls_MenuCursorPosition};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_base_movement_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/base_movement/in/Teleport")));
            SteamVR_Actions.p_base_movement_ConfirmTarget = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/base_movement/in/ConfirmTarget")));
            SteamVR_Actions.p_base_movement_StopRobot = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/base_movement/in/StopRobot")));
            SteamVR_Actions.p_base_movement_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/base_movement/in/Pose")));
            SteamVR_Actions.p_base_movement_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/base_movement/in/Squeeze")));
            SteamVR_Actions.p_base_movement_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/base_movement/in/HeadsetOnHead")));
            SteamVR_Actions.p_base_movement_ThumbXY = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/base_movement/in/ThumbXY")));
            SteamVR_Actions.p_base_movement_StrafeTarget = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/base_movement/in/StrafeTarget")));
            SteamVR_Actions.p_base_movement_TurnCamLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/base_movement/in/TurnCamLeft")));
            SteamVR_Actions.p_base_movement_TurnCamRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/base_movement/in/TurnCamRight")));
            SteamVR_Actions.p_base_movement_moveForward = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/base_movement/in/moveForward")));
            SteamVR_Actions.p_base_movement_moveBackward = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/base_movement/in/moveBackward")));
            SteamVR_Actions.p_base_movement_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/base_movement/out/Haptic")));
            SteamVR_Actions.p_arm_movement_targetPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/arm_movement/in/targetPosition")));
            SteamVR_Actions.p_arm_movement_pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/arm_movement/in/pose")));
            SteamVR_Actions.p_arm_movement_targetConfirm = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/arm_movement/in/targetConfirm")));
            SteamVR_Actions.p_arm_movement_changeControlMode = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/arm_movement/in/changeControlMode")));
            SteamVR_Actions.p_arm_movement_actuateGripper = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/arm_movement/in/actuateGripper")));
            SteamVR_Actions.p_arm_movement_stopArm = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/arm_movement/in/stopArm")));
            SteamVR_Actions.p_arm_movement_targetRotationAndHeight = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/arm_movement/in/targetRotationAndHeight")));
            SteamVR_Actions.p_arm_movement_NoResponse = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/arm_movement/in/NoResponse")));
            SteamVR_Actions.p_arm_movement_YesResponse = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/arm_movement/in/YesResponse")));
            SteamVR_Actions.p_common_controls_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/common_controls/in/Pose")));
            SteamVR_Actions.p_common_controls_ChangeActionSet = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/common_controls/in/ChangeActionSet")));
            SteamVR_Actions.p_common_controls_Select = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/common_controls/in/Select")));
            SteamVR_Actions.p_common_controls_Activate = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/common_controls/in/Activate")));
            SteamVR_Actions.p_common_controls_Interface = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/common_controls/in/Interface")));
            SteamVR_Actions.p_common_controls_ActivateMenu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/common_controls/in/ActivateMenu")));
            SteamVR_Actions.p_common_controls_SelectMenu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/common_controls/in/SelectMenu")));
            SteamVR_Actions.p_common_controls_MenuCursorPosition = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/common_controls/in/MenuCursorPosition")));
        }
    }
}
