//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class GripperRequestMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/GripperRequest";
        public override string RosMessageName => k_RosMessageName;

        public uint mode;

        public GripperRequestMsg()
        {
            this.mode = 0;
        }

        public GripperRequestMsg(uint mode)
        {
            this.mode = mode;
        }

        public static GripperRequestMsg Deserialize(MessageDeserializer deserializer) => new GripperRequestMsg(deserializer);

        private GripperRequestMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
        }

        public override string ToString()
        {
            return "GripperRequestMsg: " +
            "\nmode: " + mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
