//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaCustom
{
    [Serializable]
    public class MoveDistanceResult : Message
    {
        public const string k_RosMessageName = "kinova_custom_actions/MoveDistance";
        public override string RosMessageName => k_RosMessageName;

        // result
        public float distance_moved;

        public MoveDistanceResult()
        {
            this.distance_moved = 0.0f;
        }

        public MoveDistanceResult(float distance_moved)
        {
            this.distance_moved = distance_moved;
        }

        public static MoveDistanceResult Deserialize(MessageDeserializer deserializer) => new MoveDistanceResult(deserializer);

        private MoveDistanceResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.distance_moved);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.distance_moved);
        }

        public override string ToString()
        {
            return "MoveDistanceResult: " +
            "\ndistance_moved: " + distance_moved.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
