//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaCustom
{
    [Serializable]
    public class PickObjectFullGoal : Message
    {
        public const string k_RosMessageName = "kinova_custom_actions/PickObjectFull";
        public override string RosMessageName => k_RosMessageName;

        // goal - 
        public Geometry.PoseMsg pre_pick_pose;

        public PickObjectFullGoal()
        {
            this.pre_pick_pose = new Geometry.PoseMsg();
        }

        public PickObjectFullGoal(Geometry.PoseMsg pre_pick_pose)
        {
            this.pre_pick_pose = pre_pick_pose;
        }

        public static PickObjectFullGoal Deserialize(MessageDeserializer deserializer) => new PickObjectFullGoal(deserializer);

        private PickObjectFullGoal(MessageDeserializer deserializer)
        {
            this.pre_pick_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pre_pick_pose);
        }

        public override string ToString()
        {
            return "PickObjectFullGoal: " +
            "\npre_pick_pose: " + pre_pick_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
