//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaCustom
{
    [Serializable]
    public class PlaceObjectGoal : Message
    {
        public const string k_RosMessageName = "kinova_custom_actions/PlaceObject";
        public override string RosMessageName => k_RosMessageName;

        // goal - 
        public Std.EmptyMsg goal;

        public PlaceObjectGoal()
        {
            this.goal = new Std.EmptyMsg();
        }

        public PlaceObjectGoal(Std.EmptyMsg goal)
        {
            this.goal = goal;
        }

        public static PlaceObjectGoal Deserialize(MessageDeserializer deserializer) => new PlaceObjectGoal(deserializer);

        private PlaceObjectGoal(MessageDeserializer deserializer)
        {
            this.goal = Std.EmptyMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goal);
        }

        public override string ToString()
        {
            return "PlaceObjectGoal: " +
            "\ngoal: " + goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
