//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaCustom
{
    [Serializable]
    public class TurnAngleGoal : Message
    {
        public const string k_RosMessageName = "kinova_custom_actions/TurnAngle";
        public override string RosMessageName => k_RosMessageName;

        // goal - 
        public float turn_angle;

        public TurnAngleGoal()
        {
            this.turn_angle = 0.0f;
        }

        public TurnAngleGoal(float turn_angle)
        {
            this.turn_angle = turn_angle;
        }

        public static TurnAngleGoal Deserialize(MessageDeserializer deserializer) => new TurnAngleGoal(deserializer);

        private TurnAngleGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.turn_angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.turn_angle);
        }

        public override string ToString()
        {
            return "TurnAngleGoal: " +
            "\nturn_angle: " + turn_angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
