//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaCustom
{
    [Serializable]
    public class TurnAngleResult : Message
    {
        public const string k_RosMessageName = "kinova_custom_actions/TurnAngle";
        public override string RosMessageName => k_RosMessageName;

        // result
        public float angle_turned;

        public TurnAngleResult()
        {
            this.angle_turned = 0.0f;
        }

        public TurnAngleResult(float angle_turned)
        {
            this.angle_turned = angle_turned;
        }

        public static TurnAngleResult Deserialize(MessageDeserializer deserializer) => new TurnAngleResult(deserializer);

        private TurnAngleResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.angle_turned);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.angle_turned);
        }

        public override string ToString()
        {
            return "TurnAngleResult: " +
            "\nangle_turned: " + angle_turned.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
