//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class GetMeasuredGripperMovementResponse : Message
    {
        public const string k_RosMessageName = "kortex_driver/GetMeasuredGripperMovement";
        public override string RosMessageName => k_RosMessageName;

        public GripperMsg output;

        public GetMeasuredGripperMovementResponse()
        {
            this.output = new GripperMsg();
        }

        public GetMeasuredGripperMovementResponse(GripperMsg output)
        {
            this.output = output;
        }

        public static GetMeasuredGripperMovementResponse Deserialize(MessageDeserializer deserializer) => new GetMeasuredGripperMovementResponse(deserializer);

        private GetMeasuredGripperMovementResponse(MessageDeserializer deserializer)
        {
            this.output = GripperMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.output);
        }

        public override string ToString()
        {
            return "GetMeasuredGripperMovementResponse: " +
            "\noutput: " + output.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
