//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class GetMeasuredGripperMovementRequest : Message
    {
        public const string k_RosMessageName = "kortex_driver/GetMeasuredGripperMovement";
        public override string RosMessageName => k_RosMessageName;

        public GripperRequestMsg input;

        public GetMeasuredGripperMovementRequest()
        {
            this.input = new GripperRequestMsg();
        }

        public GetMeasuredGripperMovementRequest(GripperRequestMsg input)
        {
            this.input = input;
        }

        public static GetMeasuredGripperMovementRequest Deserialize(MessageDeserializer deserializer) => new GetMeasuredGripperMovementRequest(deserializer);

        private GetMeasuredGripperMovementRequest(MessageDeserializer deserializer)
        {
            this.input = GripperRequestMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.input);
        }

        public override string ToString()
        {
            return "GetMeasuredGripperMovementRequest: " +
            "\ninput: " + input.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
