//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_common_controls : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.common_controls_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChangeActionSet
        {
            get
            {
                return SteamVR_Actions.common_controls_ChangeActionSet;
            }
        }
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.common_controls_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean Activate
        {
            get
            {
                return SteamVR_Actions.common_controls_Activate;
            }
        }
        
        public virtual SteamVR_Action_Boolean Interface
        {
            get
            {
                return SteamVR_Actions.common_controls_Interface;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActivateMenu
        {
            get
            {
                return SteamVR_Actions.common_controls_ActivateMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean SelectMenu
        {
            get
            {
                return SteamVR_Actions.common_controls_SelectMenu;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MenuCursorPosition
        {
            get
            {
                return SteamVR_Actions.common_controls_MenuCursorPosition;
            }
        }
    }
}
