//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_base_movement : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.base_movement_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean ConfirmTarget
        {
            get
            {
                return SteamVR_Actions.base_movement_ConfirmTarget;
            }
        }
        
        public virtual SteamVR_Action_Boolean StopRobot
        {
            get
            {
                return SteamVR_Actions.base_movement_StopRobot;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.base_movement_Pose;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.base_movement_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.base_movement_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ThumbXY
        {
            get
            {
                return SteamVR_Actions.base_movement_ThumbXY;
            }
        }
        
        public virtual SteamVR_Action_Vector2 StrafeTarget
        {
            get
            {
                return SteamVR_Actions.base_movement_StrafeTarget;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnCamLeft
        {
            get
            {
                return SteamVR_Actions.base_movement_TurnCamLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnCamRight
        {
            get
            {
                return SteamVR_Actions.base_movement_TurnCamRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean moveForward
        {
            get
            {
                return SteamVR_Actions.base_movement_moveForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean moveBackward
        {
            get
            {
                return SteamVR_Actions.base_movement_moveBackward;
            }
        }
        
        public virtual SteamVR_Action_Boolean NextTutorial
        {
            get
            {
                return SteamVR_Actions.base_movement_NextTutorial;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.base_movement_Haptic;
            }
        }
    }
}
