//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_arm_movement : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 targetPosition
        {
            get
            {
                return SteamVR_Actions.arm_movement_targetPosition;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.arm_movement_pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean targetConfirm
        {
            get
            {
                return SteamVR_Actions.arm_movement_targetConfirm;
            }
        }
        
        public virtual SteamVR_Action_Boolean changeControlMode
        {
            get
            {
                return SteamVR_Actions.arm_movement_changeControlMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean actuateGripper
        {
            get
            {
                return SteamVR_Actions.arm_movement_actuateGripper;
            }
        }
        
        public virtual SteamVR_Action_Boolean stopArm
        {
            get
            {
                return SteamVR_Actions.arm_movement_stopArm;
            }
        }
        
        public virtual SteamVR_Action_Vector2 targetRotationAndHeight
        {
            get
            {
                return SteamVR_Actions.arm_movement_targetRotationAndHeight;
            }
        }
    }
}
