//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_arm_movement : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 armZRotation
        {
            get
            {
                return SteamVR_Actions.arm_movement_armZRotation;
            }
        }
        
        public virtual SteamVR_Action_Boolean armUp
        {
            get
            {
                return SteamVR_Actions.arm_movement_armUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean armDown
        {
            get
            {
                return SteamVR_Actions.arm_movement_armDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean changeActionSet
        {
            get
            {
                return SteamVR_Actions.arm_movement_changeActionSet;
            }
        }
        
        public virtual SteamVR_Action_Vector2 armXY
        {
            get
            {
                return SteamVR_Actions.arm_movement_armXY;
            }
        }
        
        public virtual SteamVR_Action_Boolean armXYEnable
        {
            get
            {
                return SteamVR_Actions.arm_movement_armXYEnable;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.arm_movement_pose;
            }
        }
        
        public virtual SteamVR_Action_Vector2 scroll
        {
            get
            {
                return SteamVR_Actions.arm_movement_scroll;
            }
        }
    }
}
